"""sync models to db

Revision ID: 1bbe53a3c7d9
Revises: a3d69384e76e
Create Date: 2026-06-20 12:38:02.689269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bbe53a3c7d9'
down_revision: Union[str, None] = 'a3d69384e76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    # categories.organization_id — nullable first, backfill, then NOT NULL
    op.add_column('categories', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute("UPDATE categories SET organization_id = '00000000-0000-0000-0000-000000000001' WHERE organization_id IS NULL")
    op.alter_column('categories', 'organization_id', nullable=False)
    op.create_foreign_key(None, 'categories', 'organizations', ['organization_id'], ['id'])
    op.alter_column('enrichment_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('enrichment_queue', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('invoice_items', sa.Column('matched_product_id', sa.UUID(), nullable=True))
    op.add_column('invoice_items', sa.Column('match_method', sa.VARCHAR(length=20), nullable=True))
    op.add_column('invoice_items', sa.Column('manufacturer_code', sa.VARCHAR(length=100), nullable=True))
    op.add_column('invoice_items', sa.Column('status', sa.VARCHAR(length=20), nullable=True))
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'invoice_items', 'products', ['matched_product_id'], ['id'])
    op.add_column('invoices', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['created_by'], ['id'])
    op.drop_index('ix_parser_configs_organization_id', table_name='parser_configs')
    op.drop_column('parser_configs', 'updated_at')
    op.add_column('products', sa.Column('internal_sku', sa.VARCHAR(length=100), nullable=True))
    op.add_column('products', sa.Column('pylon_code', sa.VARCHAR(length=255), nullable=True))
    op.alter_column('products', 'rag_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_products_active', table_name='products', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_products_desc_norm_fts', table_name='products', postgresql_using='gin')
    op.drop_index('idx_products_description_fts', table_name='products', postgresql_using='gin')
    op.drop_column('scrape_configs', 'updated_at')
    op.drop_index('idx_supplier_agreements_supplier', table_name='supplier_agreements')
    op.drop_constraint('supplier_contacts_supplier_id_fkey', 'supplier_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_contacts', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_column('supplier_contacts', 'updated_at')
    op.drop_index('idx_supplier_rules_supplier', table_name='supplier_rules')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('idx_supplier_rules_supplier', 'supplier_rules', ['supplier_id', 'is_active'], unique=False)
    op.add_column('supplier_contacts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'supplier_contacts', type_='foreignkey')
    op.create_foreign_key('supplier_contacts_supplier_id_fkey', 'supplier_contacts', 'suppliers', ['supplier_id'], ['id'])
    op.create_index('idx_supplier_agreements_supplier', 'supplier_agreements', ['supplier_id'], unique=False)
    op.add_column('scrape_configs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('idx_products_description_fts', 'products', [sa.text("to_tsvector('english'::regconfig, description)")], unique=False, postgresql_using='gin')
    op.create_index('idx_products_desc_norm_fts', 'products', [sa.text("to_tsvector('english'::regconfig, description_normalized)")], unique=False, postgresql_using='gin')
    op.create_index('idx_products_active', 'products', ['supplier_id', 'supplier_code'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('products', 'rag_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('products', 'pylon_code')
    op.drop_column('products', 'internal_sku')
    op.add_column('parser_configs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('ix_parser_configs_organization_id', 'parser_configs', ['organization_id'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'created_by')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('invoice_items', 'status')
    op.drop_column('invoice_items', 'manufacturer_code')
    op.drop_column('invoice_items', 'match_method')
    op.drop_column('invoice_items', 'matched_product_id')
    op.alter_column('enrichment_queue', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('enrichment_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'organization_id')
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###
