"""v2.1_initial_schema_15_tables

Revision ID: 2d4e37fb6571
Revises: 4b067b309b23
Create Date: 2026-06-21 01:22:08.759416
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d4e37fb6571'
down_revision: Union[str, None] = '4b067b309b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('vat_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False, comment='Table/entity name'),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_al_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_al_company', 'audit_logs', ['company_id'], unique=False)
    op.create_index('idx_al_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_al_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_al_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('enrichment_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Diff of changes applied'),
    sa.Column('applied_by', sa.UUID(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ee_company', 'enrichment_events', ['company_id'], unique=False)
    op.create_index('idx_ee_product', 'enrichment_events', ['product_id'], unique=False)
    op.create_index('idx_ee_source', 'enrichment_events', ['source_type'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('export_type', sa.VARCHAR(length=50), nullable=False, comment='e.g. products, price_list'),
    sa.Column('export_version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('file_format', sa.VARCHAR(length=10), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True, comment='MinIO object key for export output'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ej_company', 'export_jobs', ['company_id'], unique=False)
    op.create_index('idx_ej_status', 'export_jobs', ['status'], unique=False)
    op.create_index('idx_ej_type', 'export_jobs', ['export_type'], unique=False)
    op.create_table('inbound_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False, comment='MinIO object key'),
    sa.Column('sha256', sa.VARCHAR(length=64), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=500), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inbound_files_company', 'inbound_files', ['company_id'], unique=False)
    op.create_index('idx_inbound_files_sha256', 'inbound_files', ['sha256'], unique=False)
    op.create_index('idx_inbound_files_supplier', 'inbound_files', ['supplier_id'], unique=False)
    op.create_index('idx_inbound_files_type', 'inbound_files', ['file_type'], unique=False)
    op.create_table('product_supplier_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku_normalized', sa.VARCHAR(length=255), nullable=False, comment='Normalized SKU (unique per supplier)'),
    sa.Column('supplier_sku_raw_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of raw SKU examples'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_history_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Price history snapshot'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'supplier_sku_normalized', name='uq_sku_per_supplier')
    )
    op.create_index('idx_psl_company', 'product_supplier_links', ['company_id'], unique=False)
    op.create_index('idx_psl_product', 'product_supplier_links', ['product_id'], unique=False)
    op.create_index('idx_psl_sku', 'product_supplier_links', ['supplier_sku_normalized'], unique=False)
    op.create_index('idx_psl_supplier', 'product_supplier_links', ['supplier_id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('entity_ref', sa.VARCHAR(length=255), nullable=True, comment='Polymorphic reference: table_name:pk'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), server_default=sa.text("'MEDIUM'"), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rt_assigned', 'review_tasks', ['assigned_to'], unique=False)
    op.create_index('idx_rt_company', 'review_tasks', ['company_id'], unique=False)
    op.create_index('idx_rt_priority', 'review_tasks', ['priority'], unique=False)
    op.create_index('idx_rt_status', 'review_tasks', ['status'], unique=False)
    op.create_index('idx_rt_type', 'review_tasks', ['task_type'], unique=False)
    op.create_table('supplier_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False, comment='MinIO object key'),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('extracted_text_object_key', sa.Text(), nullable=True, comment='MinIO key for extracted text'),
    sa.Column('embedding_ref', sa.VARCHAR(length=255), nullable=True, comment='Vector embedding reference'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_supplier_docs_company', 'supplier_documents', ['company_id'], unique=False)
    op.create_index('idx_supplier_docs_supplier', 'supplier_documents', ['supplier_id'], unique=False)
    op.create_index('idx_supplier_docs_type', 'supplier_documents', ['doc_type'], unique=False)
    op.create_table('cost_updates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_supplier_link_id', sa.UUID(), nullable=True),
    sa.Column('old_cost', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('new_cost', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_supplier_link_id'], ['product_supplier_links.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cu_company', 'cost_updates', ['company_id'], unique=False)
    op.create_index('idx_cu_product', 'cost_updates', ['product_id'], unique=False)
    op.create_index('idx_cu_status', 'cost_updates', ['status'], unique=False)
    op.create_table('parsed_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('inbound_file_id', sa.UUID(), nullable=False),
    sa.Column('doc_kind', sa.VARCHAR(length=20), nullable=False),
    sa.Column('parse_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('parser_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('header_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Date, doc_number, totals'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inbound_file_id'], ['inbound_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parsed_docs_company', 'parsed_documents', ['company_id'], unique=False)
    op.create_index('idx_parsed_docs_inbound', 'parsed_documents', ['inbound_file_id'], unique=False)
    op.create_index('idx_parsed_docs_kind', 'parsed_documents', ['doc_kind'], unique=False)
    op.create_index('idx_parsed_docs_status', 'parsed_documents', ['parse_status'], unique=False)
    op.create_table('parsed_line_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parsed_document_id', sa.UUID(), nullable=False),
    sa.Column('line_index', sa.SmallInteger(), nullable=False),
    sa.Column('supplier_sku_raw', sa.VARCHAR(length=255), nullable=True),
    sa.Column('supplier_sku_normalized', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_normalized', sa.Text(), nullable=True),
    sa.Column('qty', sa.DECIMAL(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('line_total', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('vat_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('extraction_source', sa.VARCHAR(length=20), nullable=False),
    sa.Column('extraction_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pli_company', 'parsed_line_items', ['company_id'], unique=False)
    op.create_index('idx_pli_parsed_doc', 'parsed_line_items', ['parsed_document_id'], unique=False)
    op.create_index('idx_pli_sku', 'parsed_line_items', ['supplier_sku_normalized'], unique=False)
    op.create_table('match_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parsed_line_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_supplier_link_id', sa.UUID(), nullable=True),
    sa.Column('decision_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('candidates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parsed_line_item_id'], ['parsed_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_supplier_link_id'], ['product_supplier_links.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_md_company', 'match_decisions', ['company_id'], unique=False)
    op.create_index('idx_md_line_item', 'match_decisions', ['parsed_line_item_id'], unique=False)
    op.create_index('idx_md_product', 'match_decisions', ['product_id'], unique=False)
    op.create_index('idx_md_type', 'match_decisions', ['decision_type'], unique=False)
    op.drop_index(op.f('idx_invoices_supplier_status'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('parser_configs')
    op.drop_table('organizations')
    op.drop_table('scrape_configs')
    op.drop_table('supplier_contacts')
    op.drop_table('categories')
    op.drop_table('supplier_agreements')
    op.drop_index(op.f('idx_review_open_priority'), table_name='review_queue', postgresql_where="((status)::text = ANY ((ARRAY['open'::character varying, 'in_progress'::character varying])::text[]))")
    op.drop_table('review_queue')
    op.drop_index(op.f('idx_price_history_product'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('audit_log')
    op.drop_table('product_specifications')
    op.drop_table('supplier_rules')
    op.drop_index(op.f('idx_source_active'), table_name='product_source_data', postgresql_where='is_active')
    op.drop_table('product_source_data')
    op.drop_index(op.f('idx_invoice_items_invoice'), table_name='invoice_items')
    op.drop_index(op.f('idx_invoice_items_product'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_table('export_logs')
    op.drop_table('enrichment_queue')
    op.add_column('products', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('canonical_name', sa.VARCHAR(length=500), nullable=False))
    op.add_column('products', sa.Column('internal_code', sa.VARCHAR(length=100), nullable=True, comment='EDM internal code (e.g., ERG-00000001)'))
    op.add_column('products', sa.Column('technical_specs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('category_path', sa.VARCHAR(length=500), nullable=True, comment='Hierarchical path e.g. K1/K2/K3'))
    op.add_column('products', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=False))
    op.drop_index(op.f('idx_products_categories'), table_name='products')
    op.drop_index(op.f('idx_products_ean'), table_name='products')
    op.drop_index(op.f('idx_products_manufacturer'), table_name='products')
    op.drop_index(op.f('idx_products_supplier_code'), table_name='products')
    op.drop_constraint(op.f('products_ergalyon_code_key'), 'products', type_='unique')
    op.drop_constraint(op.f('uq_supplier_code'), 'products', type_='unique')
    op.create_index('idx_products_company', 'products', ['company_id'], unique=False)
    op.create_index('idx_products_internal_code', 'products', ['internal_code'], unique=False)
    op.create_index('idx_products_status', 'products', ['status'], unique=False)
    op.drop_constraint(op.f('products_category_k1_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_supplier_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_organization_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_k2_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_k3_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.drop_column('products', 'pylon_code')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'organization_id')
    op.drop_column('products', 'ergalyon_code')
    op.drop_column('products', 'manufacturer_id')
    op.drop_column('products', 'specs_json')
    op.drop_column('products', 'category_confidence')
    op.drop_column('products', 'category_k2_id')
    op.drop_column('products', 'current_price')
    op.drop_column('products', 'supplier_code')
    op.drop_column('products', 'data_completeness_score')
    op.drop_column('products', 'manufacturer_code')
    op.drop_column('products', 'description')
    op.drop_column('products', 'ean')
    op.drop_column('products', 'supplier_id')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'manufacturer_flag')
    op.drop_column('products', 'embedding')
    op.drop_column('products', 'category_k1_id')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'rag_context')
    op.drop_column('products', 'description_normalized')
    op.drop_column('products', 'price_currency')
    op.drop_column('products', 'internal_sku')
    op.drop_column('products', 'category_k3_id')
    op.add_column('suppliers', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('suppliers', sa.Column('vat_number', sa.VARCHAR(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('tax_profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AADE / tax authority profile'))
    op.add_column('suppliers', sa.Column('contacts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of contact persons'))
    op.add_column('suppliers', sa.Column('default_currency', sa.VARCHAR(length=3), server_default=sa.text("'EUR'"), nullable=False))
    op.add_column('suppliers', sa.Column('default_parser', sa.VARCHAR(length=50), nullable=True, comment='Default parsing profile'))
    op.add_column('suppliers', sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Code normalization & validation rules'))
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('suppliers', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('suppliers_afm_key'), 'suppliers', type_='unique')
    op.drop_constraint(op.f('suppliers_code_key'), 'suppliers', type_='unique')
    op.create_index('idx_suppliers_company', 'suppliers', ['company_id'], unique=False)
    op.create_index('idx_suppliers_vat', 'suppliers', ['vat_number'], unique=False)
    op.drop_constraint(op.f('suppliers_organization_id_fkey'), 'suppliers', type_='foreignkey')
    op.drop_constraint(op.f('fk_suppliers_default_parser_id'), 'suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    op.drop_column('suppliers', 'default_unit')
    op.drop_column('suppliers', 'default_parser_id')
    op.drop_column('suppliers', 'default_vat_rate')
    op.drop_column('suppliers', 'organization_id')
    op.drop_column('suppliers', 'country')
    op.drop_column('suppliers', 'contact_email')
    op.drop_column('suppliers', 'address')
    op.drop_column('suppliers', 'pylon_supplier_code')
    op.drop_column('suppliers', 'aade_data')
    op.drop_column('suppliers', 'afm')
    op.drop_column('suppliers', 'website')
    op.drop_column('suppliers', 'default_wholesale_markup')
    op.drop_column('suppliers', 'code_normalization_rules')
    op.drop_column('suppliers', 'default_brand')
    op.drop_column('suppliers', 'code')
    op.drop_column('suppliers', 'contact_phone')
    op.drop_column('suppliers', 'default_retail_markup')
    op.drop_column('suppliers', 'deleted_at')
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'contact_persons')
    op.drop_column('suppliers', 'legal_name')
    op.drop_column('suppliers', 'language')
    op.drop_column('suppliers', 'payment_terms')
    op.drop_column('suppliers', 'brands')
    op.drop_column('suppliers', 'supplier_type')
    op.drop_column('suppliers', 'status')
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('idx_users_company', 'users', ['company_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_user_company_email', 'users', ['company_id', 'email'])
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.drop_column('users', 'organization_id')

    # ── CHECK constraints (inline column constraints not detected by autogenerate) ──
    # Users
    op.create_check_constraint("chk_users_role", "users", "role IN ('admin','operator','viewer')")
    # Products
    op.create_check_constraint("chk_products_status", "products", "status IN ('active','provisional','archived')")
    # SupplierDocuments
    op.create_check_constraint("chk_supplier_docs_type", "supplier_documents", "doc_type IN ('agreement','catalog','price_list','other')")
    # InboundFiles
    op.create_check_constraint("chk_inbound_files_type", "inbound_files", "file_type IN ('pdf','xml','xlsx','img')")
    # ParsedDocuments
    op.create_check_constraint("chk_parsed_docs_kind", "parsed_documents", "doc_kind IN ('invoice','offer','catalog','unknown')")
    op.create_check_constraint("chk_parsed_docs_status", "parsed_documents", "parse_status IN ('pending','success','needs_review','failed')")
    # ParsedLineItems
    op.create_check_constraint("chk_pli_source", "parsed_line_items", "extraction_source IN ('xml','pdf_ocr','pdf_table','manual')")
    # MatchDecisions
    op.create_check_constraint("chk_md_decision_type", "match_decisions", "decision_type IN ('auto_exact','auto_suggested','manual_confirm','manual_override')")
    # EnrichmentEvents
    op.create_check_constraint("chk_ee_source", "enrichment_events", "source_type IN ('xml','list','catalog','manual','scrape')")
    # ReviewTasks
    op.create_check_constraint("chk_rt_task_type", "review_tasks", "task_type IN ('parse_fix','match_confirm','enrichment_confirm','export_validate')")
    op.create_check_constraint("chk_rt_status", "review_tasks", "status IN ('open','in_progress','done')")
    op.create_check_constraint("chk_rt_priority", "review_tasks", "priority IN ('CRITICAL','HIGH','MEDIUM','LOW')")
    # CostUpdates
    op.create_check_constraint("chk_cu_source", "cost_updates", "source IN ('invoice','catalog','scrape','manual')")
    op.create_check_constraint("chk_cu_status", "cost_updates", "status IN ('pending','approved','rejected')")
    # AuditLogs
    op.create_check_constraint("chk_al_action", "audit_logs", "action IN ('create','update','delete','match','enrich','export')")
    # ExportJobs
    op.create_check_constraint("chk_ej_format", "export_jobs", "file_format IN ('csv','xlsx','json','xml')")
    op.create_check_constraint("chk_ej_status", "export_jobs", "status IN ('pending','processing','completed','failed')")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ── Drop CHECK constraints added in upgrade ──
    op.drop_check_constraint("chk_ej_status", "export_jobs")
    op.drop_check_constraint("chk_ej_format", "export_jobs")
    op.drop_check_constraint("chk_al_action", "audit_logs")
    op.drop_check_constraint("chk_cu_status", "cost_updates")
    op.drop_check_constraint("chk_cu_source", "cost_updates")
    op.drop_check_constraint("chk_rt_priority", "review_tasks")
    op.drop_check_constraint("chk_rt_status", "review_tasks")
    op.drop_check_constraint("chk_rt_task_type", "review_tasks")
    op.drop_check_constraint("chk_ee_source", "enrichment_events")
    op.drop_check_constraint("chk_md_decision_type", "match_decisions")
    op.drop_check_constraint("chk_pli_source", "parsed_line_items")
    op.drop_check_constraint("chk_parsed_docs_status", "parsed_documents")
    op.drop_check_constraint("chk_parsed_docs_kind", "parsed_documents")
    op.drop_check_constraint("chk_inbound_files_type", "inbound_files")
    op.drop_check_constraint("chk_supplier_docs_type", "supplier_documents")
    op.drop_check_constraint("chk_products_status", "products")
    op.drop_check_constraint("chk_users_role", "users")

    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint('uq_user_company_email', 'users', type_='unique')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_company', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'company_id')
    op.add_column('suppliers', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('supplier_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('brands', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('language', sa.VARCHAR(length=20), server_default=sa.text("'Greek'::character varying"), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('contact_persons', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('default_retail_markup', sa.NUMERIC(precision=8, scale=2), server_default=sa.text('55.00'), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('default_brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('code_normalization_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('default_wholesale_markup', sa.NUMERIC(precision=8, scale=2), server_default=sa.text('30.00'), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('afm', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('aade_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('pylon_supplier_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('country', sa.VARCHAR(length=100), server_default=sa.text("'Greece'::character varying"), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('default_vat_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('24.00'), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('default_parser_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('default_unit', sa.VARCHAR(length=20), server_default=sa.text("'ΤΕΜ'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_suppliers_default_parser_id'), 'suppliers', 'parser_configs', ['default_parser_id'], ['id'])
    op.create_foreign_key(op.f('suppliers_organization_id_fkey'), 'suppliers', 'organizations', ['organization_id'], ['id'])
    op.drop_index('idx_suppliers_vat', table_name='suppliers')
    op.drop_index('idx_suppliers_company', table_name='suppliers')
    op.create_unique_constraint(op.f('suppliers_code_key'), 'suppliers', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('suppliers_afm_key'), 'suppliers', ['afm'], postgresql_nulls_not_distinct=False)
    op.drop_column('suppliers', 'is_deleted')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'is_active')
    op.drop_column('suppliers', 'rules_json')
    op.drop_column('suppliers', 'default_parser')
    op.drop_column('suppliers', 'default_currency')
    op.drop_column('suppliers', 'contacts_json')
    op.drop_column('suppliers', 'tax_profile_json')
    op.drop_column('suppliers', 'vat_number')
    op.drop_column('suppliers', 'company_id')
    op.add_column('products', sa.Column('category_k3_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('internal_sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('description_normalized', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('rag_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category_k1_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('manufacturer_flag', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('ean', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('manufacturer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('data_completeness_score', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('supplier_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category_k2_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category_confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('specs_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('manufacturer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('ergalyon_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('pylon_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_k3_id_fkey'), 'products', 'categories', ['category_k3_id'], ['id'])
    op.create_foreign_key(op.f('products_category_k2_id_fkey'), 'products', 'categories', ['category_k2_id'], ['id'])
    op.create_foreign_key(op.f('products_organization_id_fkey'), 'products', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('products_supplier_id_fkey'), 'products', 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('products_category_k1_id_fkey'), 'products', 'categories', ['category_k1_id'], ['id'])
    op.drop_index('idx_products_status', table_name='products')
    op.drop_index('idx_products_internal_code', table_name='products')
    op.drop_index('idx_products_company', table_name='products')
    op.create_unique_constraint(op.f('uq_supplier_code'), 'products', ['supplier_id', 'supplier_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_ergalyon_code_key'), 'products', ['ergalyon_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_products_supplier_code'), 'products', ['supplier_id', 'supplier_code'], unique=False)
    op.create_index(op.f('idx_products_manufacturer'), 'products', ['manufacturer_code'], unique=False)
    op.create_index(op.f('idx_products_ean'), 'products', ['ean'], unique=False)
    op.create_index(op.f('idx_products_categories'), 'products', ['category_k1_id', 'category_k2_id', 'category_k3_id'], unique=False)
    op.drop_column('products', 'status')
    op.drop_column('products', 'category_path')
    op.drop_column('products', 'technical_specs_json')
    op.drop_column('products', 'internal_code')
    op.drop_column('products', 'canonical_name')
    op.drop_column('products', 'company_id')
    op.create_table('enrichment_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enrichment_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("enrichment_level::text = ANY (ARRAY['XML'::character varying, 'CATALOG'::character varying, 'PRODUCT_LIST'::character varying, 'MANUAL'::character varying, 'WEB_SCRAPING'::character varying]::text[])", name=op.f('enrichment_queue_enrichment_level_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying]::text[])", name=op.f('enrichment_queue_status_check')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('enrichment_queue_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('enrichment_queue_pkey'))
    )
    op.create_table('export_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('export_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('file_format', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying]::text[])", name=op.f('export_logs_status_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('export_logs_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('export_logs_pkey'))
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_supplier_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('normalized_supplier_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('raw_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('line_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('vat_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('match_confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('matched_product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('match_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('manufacturer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('invoice_items_invoice_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], name=op.f('invoice_items_matched_product_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('invoice_items_organization_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('invoice_items_product_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_items_pkey'))
    )
    op.create_index(op.f('idx_invoice_items_product'), 'invoice_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_invoice_items_invoice'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('product_source_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_priority', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('source_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint("source::text = ANY (ARRAY['xml'::character varying, 'catalog'::character varying, 'manual'::character varying, 'scraping'::character varying]::text[])", name=op.f('product_source_data_source_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('product_source_data_organization_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_source_data_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_source_data_pkey'))
    )
    op.create_index(op.f('idx_source_active'), 'product_source_data', ['product_id', 'field_name'], unique=False, postgresql_where='is_active')
    op.create_table('supplier_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('priority', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint("rule_type::text = ANY (ARRAY['code_normalization'::character varying, 'field_mapping'::character varying, 'validation'::character varying, 'enrichment_hint'::character varying]::text[])", name=op.f('supplier_rules_rule_type_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('supplier_rules_organization_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_rules_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_rules_pkey'))
    )
    op.create_table('product_specifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('spec_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('spec_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint("source::text = ANY (ARRAY['xml'::character varying, 'catalog'::character varying, 'manual'::character varying, 'scraping'::character varying]::text[])", name=op.f('product_specifications_source_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('product_specifications_organization_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_specifications_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_specifications_pkey')),
    sa.UniqueConstraint('product_id', 'spec_key', name=op.f('uq_product_spec'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('audit_log_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('price_history_invoice_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('price_history_organization_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('price_history_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('price_history_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_history_pkey'))
    )
    op.create_index(op.f('idx_price_history_product'), 'price_history', ['product_id', 'recorded_at'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('invoice_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('review_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('prompt_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint("priority::text = ANY (ARRAY['CRITICAL'::character varying, 'HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying]::text[])", name=op.f('review_queue_priority_check')),
    sa.CheckConstraint("resolution::text = ANY (ARRAY['approved'::character varying, 'edited'::character varying, 'rejected'::character varying]::text[])", name=op.f('review_queue_resolution_check')),
    sa.CheckConstraint("review_type::text = ANY (ARRAY['low_confidence'::character varying, 'duplicate'::character varying, 'missing_manufacturer_code'::character varying, 'price_anomaly'::character varying, 'new_supplier'::character varying]::text[])", name=op.f('review_queue_review_type_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'dismissed'::character varying]::text[])", name=op.f('review_queue_status_check')),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], name=op.f('review_queue_invoice_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('review_queue_organization_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('review_queue_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('review_queue_pkey'))
    )
    op.create_index(op.f('idx_review_open_priority'), 'review_queue', ['status', 'priority'], unique=False, postgresql_where="((status)::text = ANY ((ARRAY['open'::character varying, 'in_progress'::character varying])::text[]))")
    op.create_table('supplier_agreements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rag_index_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('indexed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('supplier_agreements_organization_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_agreements_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_agreements_pkey'))
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('level', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint('level = 1 AND parent_id IS NULL OR level > 1 AND parent_id IS NOT NULL', name=op.f('chk_level1_no_parent')),
    sa.CheckConstraint('level = ANY (ARRAY[1, 2, 3])', name=op.f('categories_level_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('categories_organization_id_fkey')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('categories_parent_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_table('supplier_contacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('supplier_contacts_organization_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_contacts_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_contacts_pkey'))
    )
    op.create_table('scrape_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("strategy::text = ANY (ARRAY['CRAWL4AI'::character varying, 'PLAYWRIGHT'::character varying, 'SCRAPY'::character varying, 'MANUAL'::character varying]::text[])", name=op.f('scrape_configs_strategy_check')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('scrape_configs_organization_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('scrape_configs_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scrape_configs_pkey'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('aade_afm', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey')),
    sa.UniqueConstraint('aade_afm', name=op.f('organizations_aade_afm_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('parser_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parser_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('parser_configs_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('parser_configs_pkey'))
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('parsed_data_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parsing_confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("document_type::text = ANY (ARRAY['invoice'::character varying, 'offer'::character varying, 'catalog'::character varying]::text[])", name=op.f('invoices_document_type_check')),
    sa.CheckConstraint("file_format::text = ANY (ARRAY['xml'::character varying, 'pdf'::character varying, 'image'::character varying, 'excel'::character varying]::text[])", name=op.f('invoices_file_format_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['uploaded'::character varying, 'parsing'::character varying, 'parsed'::character varying, 'normalized'::character varying, 'enriched'::character varying, 'reviewed'::character varying, 'exported'::character varying, 'failed'::character varying]::text[])", name=op.f('invoices_status_check')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('invoices_created_by_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('invoices_organization_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('invoices_supplier_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey'))
    )
    op.create_index(op.f('idx_invoices_supplier_status'), 'invoices', ['supplier_id', 'status'], unique=False)
    op.drop_index('idx_md_type', table_name='match_decisions')
    op.drop_index('idx_md_product', table_name='match_decisions')
    op.drop_index('idx_md_line_item', table_name='match_decisions')
    op.drop_index('idx_md_company', table_name='match_decisions')
    op.drop_table('match_decisions')
    op.drop_index('idx_pli_sku', table_name='parsed_line_items')
    op.drop_index('idx_pli_parsed_doc', table_name='parsed_line_items')
    op.drop_index('idx_pli_company', table_name='parsed_line_items')
    op.drop_table('parsed_line_items')
    op.drop_index('idx_parsed_docs_status', table_name='parsed_documents')
    op.drop_index('idx_parsed_docs_kind', table_name='parsed_documents')
    op.drop_index('idx_parsed_docs_inbound', table_name='parsed_documents')
    op.drop_index('idx_parsed_docs_company', table_name='parsed_documents')
    op.drop_table('parsed_documents')
    op.drop_index('idx_cu_status', table_name='cost_updates')
    op.drop_index('idx_cu_product', table_name='cost_updates')
    op.drop_index('idx_cu_company', table_name='cost_updates')
    op.drop_table('cost_updates')
    op.drop_index('idx_supplier_docs_type', table_name='supplier_documents')
    op.drop_index('idx_supplier_docs_supplier', table_name='supplier_documents')
    op.drop_index('idx_supplier_docs_company', table_name='supplier_documents')
    op.drop_table('supplier_documents')
    op.drop_index('idx_rt_type', table_name='review_tasks')
    op.drop_index('idx_rt_status', table_name='review_tasks')
    op.drop_index('idx_rt_priority', table_name='review_tasks')
    op.drop_index('idx_rt_company', table_name='review_tasks')
    op.drop_index('idx_rt_assigned', table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index('idx_psl_supplier', table_name='product_supplier_links')
    op.drop_index('idx_psl_sku', table_name='product_supplier_links')
    op.drop_index('idx_psl_product', table_name='product_supplier_links')
    op.drop_index('idx_psl_company', table_name='product_supplier_links')
    op.drop_table('product_supplier_links')
    op.drop_index('idx_inbound_files_type', table_name='inbound_files')
    op.drop_index('idx_inbound_files_supplier', table_name='inbound_files')
    op.drop_index('idx_inbound_files_sha256', table_name='inbound_files')
    op.drop_index('idx_inbound_files_company', table_name='inbound_files')
    op.drop_table('inbound_files')
    op.drop_index('idx_ej_type', table_name='export_jobs')
    op.drop_index('idx_ej_status', table_name='export_jobs')
    op.drop_index('idx_ej_company', table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index('idx_ee_source', table_name='enrichment_events')
    op.drop_index('idx_ee_product', table_name='enrichment_events')
    op.drop_index('idx_ee_company', table_name='enrichment_events')
    op.drop_table('enrichment_events')
    op.drop_index('idx_al_user', table_name='audit_logs')
    op.drop_index('idx_al_entity', table_name='audit_logs')
    op.drop_index('idx_al_created', table_name='audit_logs')
    op.drop_index('idx_al_company', table_name='audit_logs')
    op.drop_index('idx_al_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('companies')
    # ### end Alembic commands ###
