"""add_supplier_business_fields

Revision ID: 4b067b309b23
Revises: 1bbe53a3c7d9
Create Date: 2026-06-20 20:31:04.431527
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b067b309b23'
down_revision: Union[str, None] = '1bbe53a3c7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('code', sa.VARCHAR(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('address', sa.VARCHAR(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('country', sa.VARCHAR(length=100), nullable=False, server_default='Greece'))
    op.add_column('suppliers', sa.Column('language', sa.VARCHAR(length=20), nullable=False, server_default='Greek'))
    op.add_column('suppliers', sa.Column('supplier_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('default_vat_rate', sa.DECIMAL(precision=5, scale=2), nullable=False, server_default='24.00'))
    op.add_column('suppliers', sa.Column('default_unit', sa.VARCHAR(length=20), nullable=False, server_default='ΤΕΜ'))
    op.add_column('suppliers', sa.Column('default_wholesale_markup', sa.DECIMAL(precision=8, scale=2), nullable=False, server_default='30.00'))
    op.add_column('suppliers', sa.Column('default_retail_markup', sa.DECIMAL(precision=8, scale=2), nullable=False, server_default='55.00'))
    op.add_column('suppliers', sa.Column('brands', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('suppliers', sa.Column('default_brand', sa.VARCHAR(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('pylon_supplier_code', sa.VARCHAR(length=50), nullable=True))
    op.create_unique_constraint(None, 'suppliers', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'pylon_supplier_code')
    op.drop_column('suppliers', 'default_brand')
    op.drop_column('suppliers', 'brands')
    op.drop_column('suppliers', 'default_retail_markup')
    op.drop_column('suppliers', 'default_wholesale_markup')
    op.drop_column('suppliers', 'default_unit')
    op.drop_column('suppliers', 'default_vat_rate')
    op.drop_column('suppliers', 'supplier_type')
    op.drop_column('suppliers', 'language')
    op.drop_column('suppliers', 'country')
    op.drop_column('suppliers', 'address')
    op.drop_column('suppliers', 'code')
    # ### end Alembic commands ###
