"""add organization and users with default

Revision ID: b7c8d9e0f1a2_add_organization_and_users
Revises: 70164050bb8f
Create Date: 2026-06-20T07:21:57.054972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = '012_organizations_users'
down_revision = '70164050bb8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create organizations table
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('aade_afm', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aade_afm')
    )
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),  # TODO: add check constraint
    sa.Column('display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False, server_default=sa.text('true')),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # Add organization_id column as nullable to all relevant tables
    tables = [
        'suppliers',
        'products',
        'invoices',
        'invoice_items',
        'product_source_data',
        'product_specifications',
        'price_history',
        'supplier_rules',
        'supplier_agreements',
        'review_queue',
        'audit_log'
    ]
    for table in tables:
        op.add_column(table, sa.Column('organization_id', sa.UUID(), nullable=True))
    # Insert a default organization (we'll use a fixed UUID)
    default_org_id = '00000000-0000-0000-0000-000000000001'
    op.execute(
        f"""INSERT INTO organizations (id, name, aade_afm, address, settings, created_at, updated_at)
        VALUES ('{default_org_id}', 'Default Organization', NULL, NULL, '{{}}', now(), now())
        ON CONFLICT (id) DO NOTHING;"""
    )
    # Update existing rows to set organization_id to the default where NULL
    for table in tables:
        op.execute(
            f"UPDATE {table} SET organization_id = '{default_org_id}' WHERE organization_id IS NULL;"
        )
    # Now alter column to NOT NULL and add foreign key
    for table in tables:
        op.alter_column(table, 'organization_id', nullable=False)
        op.create_foreign_key(None, table, 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys and columns in reverse order
    tables = [
        'suppliers',
        'products',
        'invoices',
        'invoice_items',
        'product_source_data',
        'product_specifications',
        'price_history',
        'supplier_rules',
        'supplier_agreements',
        'review_queue',
        'audit_log'
    ]
    for table in reversed(tables):
        op.drop_constraint(None, table, type_='foreignkey')
        op.alter_column(table, 'organization_id', nullable=True)
        op.drop_column(table, 'organization_id')
    # Delete default organization (optional)
    op.execute("DELETE FROM organizations WHERE id = '00000000-0000-0000-0000-000000000001';")
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
